"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/init-api'
import Navbar from '@/comps/navbar'
import { useCallback } from 'react'

console.log('HI')

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const onSearch = useCallback(
    text => {
      console.log('text: ', text)
    }, []
  )

  return (
    <html lang="en">
      <body className={inter.className + ' --mt-5'}>
        <Navbar onSearch={onSearch}/>
        <div children={children}/>
        {/* hi */}
      </body>
    </html>
  )
}
